-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DB_SOCIAL_PORTAL
-- -----------------------------------------------------
-- Social portal database
DROP SCHEMA IF EXISTS `DB_SOCIAL_PORTAL` ;

-- -----------------------------------------------------
-- Schema DB_SOCIAL_PORTAL
--
-- Social portal database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_SOCIAL_PORTAL` DEFAULT CHARACTER SET utf8 ;
USE `DB_SOCIAL_PORTAL` ;

-- -----------------------------------------------------
-- Table `DB_SOCIAL_PORTAL`.`PICTRUE_T`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_SOCIAL_PORTAL`.`PICTRUE_T` ;

CREATE TABLE IF NOT EXISTS `DB_SOCIAL_PORTAL`.`PICTRUE_T` (
  `PICTRUE_ID` INT NOT NULL AUTO_INCREMENT,
  `USER_ID` INT NOT NULL,
  `IMAGE` MEDIUMBLOB NOT NULL,
  `DATE` DATETIME NOT NULL,
  PRIMARY KEY (`PICTRUE_ID`),
  INDEX `USER_FK_idx` (`USER_ID` ASC),
  CONSTRAINT `PICTRUE_USER_FK`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `DB_SOCIAL_PORTAL`.`USER_T` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SOCIAL_PORTAL`.`LANGUAGE_T`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_SOCIAL_PORTAL`.`LANGUAGE_T` ;

CREATE TABLE IF NOT EXISTS `DB_SOCIAL_PORTAL`.`LANGUAGE_T` (
  `LANGUAGE_ID` INT NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `CODE` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`LANGUAGE_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SOCIAL_PORTAL`.`USER_T`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_SOCIAL_PORTAL`.`USER_T` ;

CREATE TABLE IF NOT EXISTS `DB_SOCIAL_PORTAL`.`USER_T` (
  `USER_ID` INT NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(45) NOT NULL,
  `SECOND_NAME` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(256) NOT NULL,
  `PASSWORD` VARCHAR(255) NOT NULL,
  `PROFILE_PHOTO_ID` INT NULL,
  `MALE` BIT(1) NOT NULL DEFAULT 0,
  `PREFERRED_LANGUAGE_ID` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`USER_ID`),
  UNIQUE INDEX `USER_ID_UNIQUE` (`USER_ID` ASC),
  INDEX `PROFILE_PHOTO_FK_idx` (`PROFILE_PHOTO_ID` ASC),
  INDEX `PREFERRED_LANGUAGE_FK_idx` (`PREFERRED_LANGUAGE_ID` ASC),
  CONSTRAINT `USER_PROFILE_PHOTO_FK`
    FOREIGN KEY (`PROFILE_PHOTO_ID`)
    REFERENCES `DB_SOCIAL_PORTAL`.`PICTRUE_T` (`PICTRUE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PREFERRED_LANGUAGE_FK`
    FOREIGN KEY (`PREFERRED_LANGUAGE_ID`)
    REFERENCES `DB_SOCIAL_PORTAL`.`LANGUAGE_T` (`LANGUAGE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SOCIAL_PORTAL`.`INVITATION_T`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_SOCIAL_PORTAL`.`INVITATION_T` ;

CREATE TABLE IF NOT EXISTS `DB_SOCIAL_PORTAL`.`INVITATION_T` (
  `INVITATION_ID` INT NOT NULL AUTO_INCREMENT,
  `FROM_USER_ID` INT NOT NULL,
  `TO_USER_ID` INT NOT NULL,
  `SENDED` DATETIME NOT NULL,
  `ACCEPTED` BIT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`INVITATION_ID`),
  UNIQUE INDEX `idINVITATIONS_ID_UNIQUE` (`INVITATION_ID` ASC),
  INDEX `TO_USER_FK_idx` (`TO_USER_ID` ASC),
  INDEX `FROM_USER_FK_idx` (`FROM_USER_ID` ASC),
  CONSTRAINT `INVITATION_TO_USER_FK`
    FOREIGN KEY (`TO_USER_ID`)
    REFERENCES `DB_SOCIAL_PORTAL`.`USER_T` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `INVITATION_FROM_USER_FK`
    FOREIGN KEY (`FROM_USER_ID`)
    REFERENCES `DB_SOCIAL_PORTAL`.`USER_T` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SOCIAL_PORTAL`.`ROLE_T`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_SOCIAL_PORTAL`.`ROLE_T` ;

CREATE TABLE IF NOT EXISTS `DB_SOCIAL_PORTAL`.`ROLE_T` (
  `ROLE_ID` INT NOT NULL AUTO_INCREMENT,
  `ROLE` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ROLE_ID`),
  UNIQUE INDEX `ROLE_ID_UNIQUE` (`ROLE_ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SOCIAL_PORTAL`.`INVITATION_NOTIFICATION_T`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_SOCIAL_PORTAL`.`INVITATION_NOTIFICATION_T` ;

CREATE TABLE IF NOT EXISTS `DB_SOCIAL_PORTAL`.`INVITATION_NOTIFICATION_T` (
  `INVITATION_NOTIFICATION_ID` INT NOT NULL AUTO_INCREMENT,
  `FOR_USER_ID` INT NOT NULL,
  `INVITATION_ID` INT NOT NULL,
  PRIMARY KEY (`INVITATION_NOTIFICATION_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SOCIAL_PORTAL`.`POST_T`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_SOCIAL_PORTAL`.`POST_T` ;

CREATE TABLE IF NOT EXISTS `DB_SOCIAL_PORTAL`.`POST_T` (
  `POST_ID` INT NOT NULL AUTO_INCREMENT,
  `TEXT` TEXT NOT NULL,
  `USER_ID` INT NOT NULL,
  `DATE` DATETIME NOT NULL,
  PRIMARY KEY (`POST_ID`),
  INDEX `AUTHOR_USER_FK_idx` (`USER_ID` ASC),
  CONSTRAINT `POST_USER_FK`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `DB_SOCIAL_PORTAL`.`USER_T` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SOCIAL_PORTAL`.`COMMENT_T`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_SOCIAL_PORTAL`.`COMMENT_T` ;

CREATE TABLE IF NOT EXISTS `DB_SOCIAL_PORTAL`.`COMMENT_T` (
  `COMMENT_ID` INT NOT NULL AUTO_INCREMENT,
  `COMMENT` TINYTEXT NOT NULL,
  `USER_ID` INT NOT NULL,
  `POST_ID` INT NOT NULL COMMENT '\n',
  `DATE` DATETIME NOT NULL,
  PRIMARY KEY (`COMMENT_ID`),
  INDEX `USER_FK_idx` (`USER_ID` ASC),
  CONSTRAINT `COMMENT_USER_FK`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `DB_SOCIAL_PORTAL`.`USER_T` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SOCIAL_PORTAL`.`MESSAGE_T`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_SOCIAL_PORTAL`.`MESSAGE_T` ;

CREATE TABLE IF NOT EXISTS `DB_SOCIAL_PORTAL`.`MESSAGE_T` (
  `MESSAGE_ID` INT NOT NULL AUTO_INCREMENT,
  `FROM_USER_ID` INT NOT NULL,
  `TO_USER_ID` INT NOT NULL,
  `MESSAGE` TINYTEXT NOT NULL,
  `DATE` DATETIME NOT NULL,
  PRIMARY KEY (`MESSAGE_ID`),
  INDEX `FROM_USER_FK_idx` (`FROM_USER_ID` ASC),
  INDEX `TO_USER_FK_idx` (`TO_USER_ID` ASC),
  CONSTRAINT `MESSAGE_FROM_USER_FK`
    FOREIGN KEY (`FROM_USER_ID`)
    REFERENCES `DB_SOCIAL_PORTAL`.`USER_T` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `MESSAGE_TO_USER_FK`
    FOREIGN KEY (`TO_USER_ID`)
    REFERENCES `DB_SOCIAL_PORTAL`.`USER_T` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SOCIAL_PORTAL`.`USER_ROLES_T`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_SOCIAL_PORTAL`.`USER_ROLES_T` ;

CREATE TABLE IF NOT EXISTS `DB_SOCIAL_PORTAL`.`USER_ROLES_T` (
  `ROLE_ID` INT NOT NULL,
  `USER_ID` INT NOT NULL,
  INDEX `USERS_ROLE_USER_FK_idx` (`USER_ID` ASC),
  INDEX `USERS_ROLE_ROLE_FK_idx` (`ROLE_ID` ASC),
  CONSTRAINT `USERS_ROLE_USER_FK`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `DB_SOCIAL_PORTAL`.`USER_T` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `USERS_ROLE_ROLE_FK`
    FOREIGN KEY (`ROLE_ID`)
    REFERENCES `DB_SOCIAL_PORTAL`.`ROLE_T` (`ROLE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `DB_SOCIAL_PORTAL`;

DELIMITER $$

USE `DB_SOCIAL_PORTAL`$$
DROP TRIGGER IF EXISTS `DB_SOCIAL_PORTAL`.`INVITATION_T_AFTER_INSERT` $$
USE `DB_SOCIAL_PORTAL`$$
CREATE DEFINER = CURRENT_USER TRIGGER `DB_SOCIAL_PORTAL`.`INVITATION_T_AFTER_INSERT` AFTER INSERT ON `INVITATION_T` FOR EACH ROW
BEGIN
	INSERT INTO INVITATION_NOTIFICATION_T(FOR_USER_ID, INVITATION_ID)    
    VALUES(NEW.TO_USER_ID, NEW.INVITATION_ID);
END$$


USE `DB_SOCIAL_PORTAL`$$
DROP TRIGGER IF EXISTS `DB_SOCIAL_PORTAL`.`MESSAGE_T_AFTER_INSERT` $$
USE `DB_SOCIAL_PORTAL`$$
CREATE DEFINER = CURRENT_USER TRIGGER `DB_SOCIAL_PORTAL`.`MESSAGE_T_AFTER_INSERT` AFTER INSERT ON `MESSAGE_T` FOR EACH ROW
BEGIN
	INSERT INTO `DB_SOCIAL_PORTAL`.`NOTIFICATION_T` (`FOR_USER_ID`, `TYPE_OF_NOTIFICATION_ID`, `REFERENCE_ID`)
    VALUES (INSERTED.TO_USER_ID, 3, INSERTED.MESSAGE_ID);
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `DB_SOCIAL_PORTAL`.`LANGUAGE_T`
-- -----------------------------------------------------
START TRANSACTION;
USE `DB_SOCIAL_PORTAL`;
INSERT INTO `DB_SOCIAL_PORTAL`.`LANGUAGE_T` (`LANGUAGE_ID`, `NAME`, `CODE`) VALUES (1, 'ENGLISH', 'EN');
INSERT INTO `DB_SOCIAL_PORTAL`.`LANGUAGE_T` (`LANGUAGE_ID`, `NAME`, `CODE`) VALUES (2, 'POLISH', 'PL');

COMMIT;


-- -----------------------------------------------------
-- Data for table `DB_SOCIAL_PORTAL`.`USER_T`
-- -----------------------------------------------------
START TRANSACTION;
USE `DB_SOCIAL_PORTAL`;
INSERT INTO `DB_SOCIAL_PORTAL`.`USER_T` (`USER_ID`, `FIRST_NAME`, `SECOND_NAME`, `EMAIL`, `PASSWORD`, `PROFILE_PHOTO_ID`, `MALE`, `PREFERRED_LANGUAGE_ID`) VALUES (1, 'Bartosz', 'Ujazdowski', 'b.ujazdowski@gmail.com', '$2a$10$da7l/9VRpIPBm1z0LiONwO7wRXMs55.5QOkdpFVQ3/eqO9FBu4IXu', NULL, 1, 2);
INSERT INTO `DB_SOCIAL_PORTAL`.`USER_T` (`USER_ID`, `FIRST_NAME`, `SECOND_NAME`, `EMAIL`, `PASSWORD`, `PROFILE_PHOTO_ID`, `MALE`, `PREFERRED_LANGUAGE_ID`) VALUES (2, 'Foo', 'Bar', 'foo.bar@example.com', '$2a$10$da7l/9VRpIPBm1z0LiONwO7wRXMs55.5QOkdpFVQ3/eqO9FBu4IXu', NULL, 2, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `DB_SOCIAL_PORTAL`.`INVITATION_T`
-- -----------------------------------------------------
START TRANSACTION;
USE `DB_SOCIAL_PORTAL`;
INSERT INTO `DB_SOCIAL_PORTAL`.`INVITATION_T` (`INVITATION_ID`, `FROM_USER_ID`, `TO_USER_ID`, `SENDED`, `ACCEPTED`) VALUES (1, 1, 2, '1996-10-26 00:00:00', 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `DB_SOCIAL_PORTAL`.`ROLE_T`
-- -----------------------------------------------------
START TRANSACTION;
USE `DB_SOCIAL_PORTAL`;
INSERT INTO `DB_SOCIAL_PORTAL`.`ROLE_T` (`ROLE_ID`, `ROLE`) VALUES (1, 'USER');
INSERT INTO `DB_SOCIAL_PORTAL`.`ROLE_T` (`ROLE_ID`, `ROLE`) VALUES (2, 'MODERATOR');
INSERT INTO `DB_SOCIAL_PORTAL`.`ROLE_T` (`ROLE_ID`, `ROLE`) VALUES (3, 'ADMINISTRATOR');

COMMIT;


-- -----------------------------------------------------
-- Data for table `DB_SOCIAL_PORTAL`.`POST_T`
-- -----------------------------------------------------
START TRANSACTION;
USE `DB_SOCIAL_PORTAL`;
INSERT INTO `DB_SOCIAL_PORTAL`.`POST_T` (`POST_ID`, `TEXT`, `USER_ID`, `DATE`) VALUES (1, 'My first post', 1, '1996-10-26 00:00:00');

COMMIT;


-- -----------------------------------------------------
-- Data for table `DB_SOCIAL_PORTAL`.`COMMENT_T`
-- -----------------------------------------------------
START TRANSACTION;
USE `DB_SOCIAL_PORTAL`;
INSERT INTO `DB_SOCIAL_PORTAL`.`COMMENT_T` (`COMMENT_ID`, `COMMENT`, `USER_ID`, `POST_ID`, `DATE`) VALUES (1, 'My first comments', 1, 1, '2018-04-04 11:35:54');

COMMIT;


-- -----------------------------------------------------
-- Data for table `DB_SOCIAL_PORTAL`.`USER_ROLES_T`
-- -----------------------------------------------------
START TRANSACTION;
USE `DB_SOCIAL_PORTAL`;
INSERT INTO `DB_SOCIAL_PORTAL`.`USER_ROLES_T` (`ROLE_ID`, `USER_ID`) VALUES (1, 1);
INSERT INTO `DB_SOCIAL_PORTAL`.`USER_ROLES_T` (`ROLE_ID`, `USER_ID`) VALUES (1, 2);

COMMIT;

